# initial docker compose config; works on mac
# issue `docker-compose up -d` for a basic set up
version: '2'
services:
  elasticsearch:
    image: "elasticsearch"
    ports: 
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: "kibana"
    ports:
      - "5601:5601"
