# initial docker compose config; works on mac
# issue `docker-compose up -d` for a basic set up
version: '3.0'
services:
  elasticsearch:
    build:
      context: "es"
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports: 
      - "9200:9200"
      - "9300:9300"
  kibana:
    build:
      context: "kibana"
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "5601:5601"
  nginx:
    build:
      context: "nginx"
    ports: 
      - "80:80"
  ingester:
    build:
      context: "ingester"
    volumes:
      - /tmp/sonar-integration-test:/data
  visualise:
    build:
      context: "visualise"
    ports:
      - "3000:3000"
